### PR TITLE
Feature/common list

### PR DESCRIPTION
**Pull request by louischristner**
**Name:** feature/common-list

☑️ TDD Security
✅ Minimal Testing
✅ Accurate assignees / reviewers.

**Description:**
This pull request adds a modal component and a list component. It also updates the components style.
In order to prepare for the addition of views in the Administration page, it also adds a UserMonitor component which contains the same information than the Monitor before. The Monitor will be dedicated to the handling of the different administration views.

### CODE REVIEW

**Comment by Overblide** [comment]
Tout me paraît bon, Good job !

**Comment by hgvo9** [comment]
Hi Louis!

I have a couple of questions about the Monitor component, how is he gonna be handling other administration views ?

I've tried the modal component on my own, and I've had troubles editting informations is that normal ? There is a gif below showing me trying to edit informations of a user, but I feel like It's not updating ? You can also see my keyboard inputs in the bottom left of the screen.

Aug-02-2021 14-45-15

Apart from these questions, awesome job for the tests !

**Review by CptHash — COMMENTED** [review]
Hi ! I  just checked the code not the UI but everything seems good 👍 

I saw that @hgvo9 have found some issues with the UI so don't hesitate to ask me if you need more manual testing.

I will submit my review as a comment waiting to know what happen with the UI issue.

**Comment by louischristner** [comment]
> Hi Louis!
> 
> I have a couple of questions about the Monitor component, how is he gonna be handling other administration views ?
> 
> I've tried the modal component on my own, and I've had troubles editting informations is that normal ? There is a gif below showing me trying to edit informations of a user, but I feel like It's not updating ? You can also see my keyboard inputs in the bottom left of the screen.
> 
> Are those issues that I have are related to a back-end problem ? Perhaps the back-end is down ?
> 
> Aug-02-2021 14-45-15
> 
> Apart from these questions, awesome job !

Thanks for your feedback, I fixed the issue when updating the user information.
For the other monitor components, I was thinking about creating a navbar to navigate between the different monitors.

**Review by hgvo9 — APPROVED** [review]
All good for me Louis, the UI and the tests works, good job

**Pull request merged**
