### PR TITLE
Dropdown & Safeplace list

### PR DESCRIPTION
**Pull request by louischristner**
Following issue #9 request, I created a dropdown component.
I will update its style with every components during the current sprint.

Through merging, the Safeplace list dropped here.

### CODE REVIEW

**Comment by louischristner** [comment]
Didn't check if it builds after merging, a comma was missing.

**Comment by hgvo9** [comment]
Hey Louis,

I've tested the dropdown list, it works fine. There is a little thing, not a big issue but still worth mentioning I think, the default value of the dropdown list is always 'user', I don't know if it's needed to set the default value of the dropdown by the role of the user.

image
image

**Comment by louischristner** [comment]
> Hey Louis,
> 
> I've tested the dropdown list, it works fine. There is a little thing, not a big issue but still worth mentioning I think, the default value of the dropdown list is always 'user', I don't know if it's needed to set the default value of the dropdown by the role of the user.
> 
> What do you think ?
> 
> image
> image

My bad, I am fixing it

**Review by hgvo9 — APPROVED** [review]
All good, unless I am wrong but the code review checks are false positives, it says that props are missed in props validation but you always have an interface that you pass to your functional component where there is always an interface that specify types of a user, safeplace etc...

**Review by CptHash — APPROVED** [review]
Everything seems good! You can merge :)

**Pull request merged**
