### PR TITLE
Add length check on fields when creating & updating account

### PR DESCRIPTION
**Pull request by louischristner**
Fix empty username bug

### CODE REVIEW

**Review by CptHash — APPROVED** [review]
Everything looks good ! I will check the notifications locally :rocket:

**Comment by hgvo9** [comment]
Hi,

Thanks for the new updates, I've cloned the project and set the branch on dev, I tested and have some feedback for you @louischristner 

The login page works fine !

For the administration page, few things I've noticed that it was not normal :

- I can edit an user with empty username
- I can enter an email with the wrong format (ex: "fweo", "xclxcxclxc@", etc...)

image

Is it normal ?

**Comment by hgvo9** [comment]
It's working great with the last commit (1ef8cb6dcf3c4600fdd928016865dc22be4dc15d), thank you, I will close the issue once the back-end part of the issue is fixed.

**Comment by louischristner** [comment]
> Hi,
> 
> Thanks for the new updates, I've cloned the project and set the branch on dev, I tested and have some feedback for you @louischristner
> 
> The login page works fine !
> 
> For the administration page, few things I've noticed that it was not normal :
> 
>     * I can edit an user with empty username
> 
>     * I can enter an email with the wrong format (ex: "fweo", "xclxcxclxc@", etc...)
> 
> 
> image
> 
> Is it normal ?

@hgvo9 Thanks for raising this bug, it should be fixed now.

**Comment by louischristner** [comment]
I tried to move parameters validation in the User service as much as possible and throw an error in case of invalid parameter, so I can notify the user of the error.

**Review by hgvo9 — APPROVED** [review]
If that's okay with you @louischristner I think this pull request is ready to be closed and merge

**Pull request merged**
